// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export class WorkFlowInput {
    "user": auth$0.User;
    "date": domain$0.DateRange;
    "receive_guides_in_transit"?: boolean;
    "BrowserConf": config$0.BrowserConfig;

    /** Creates a new WorkFlowInput instance. */
    constructor($$source: Partial<WorkFlowInput> = {}) {
        if (!("user" in $$source)) {
            this["user"] = (new auth$0.User());
        }
        if (!("date" in $$source)) {
            this["date"] = (new domain$0.DateRange());
        }
        if (!("BrowserConf" in $$source)) {
            this["BrowserConf"] = (new config$0.BrowserConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkFlowInput instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkFlowInput {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField0_0($$parsedSource["user"]);
        }
        if ("date" in $$parsedSource) {
            $$parsedSource["date"] = $$createField1_0($$parsedSource["date"]);
        }
        if ("BrowserConf" in $$parsedSource) {
            $$parsedSource["BrowserConf"] = $$createField3_0($$parsedSource["BrowserConf"]);
        }
        return new WorkFlowInput($$parsedSource as Partial<WorkFlowInput>);
    }
}

// Private type creation functions
const $$createType0 = auth$0.User.createFrom;
const $$createType1 = domain$0.DateRange.createFrom;
const $$createType2 = config$0.BrowserConfig.createFrom;
