// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../../../../../io/models.js";

export class BrowserConfig {
    "LoggerOut": io$0.Writer;
    "headless"?: boolean;
    "trace"?: boolean;

    /** Creates a new BrowserConfig instance. */
    constructor($$source: Partial<BrowserConfig> = {}) {
        if (!("LoggerOut" in $$source)) {
            this["LoggerOut"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserConfig($$parsedSource as Partial<BrowserConfig>);
    }
}
