// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3181398000);
}

export function Init(): $CancellablePromise<void> {
    return $Call.ByID(1690160574);
}

export function Login(user: $models.User): $CancellablePromise<void> {
    return $Call.ByID(2130930353, user);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(734619090);
}

export function Reconfigure(cfg: config$0.BrowserConfig): $CancellablePromise<void> {
    return $Call.ByID(286575187, cfg);
}

export function Session(): $CancellablePromise<$models.Session> {
    return $Call.ByID(1458043752);
}
