// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as event$0 from "../../../../Khaym03/REG/internal/event/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as stats$0 from "../../../../Khaym03/REG/internal/workflow/queries/stats/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "bulding.browser": event$0.Empty;
            "destroying.browser": event$0.Empty;
            "guides.gather": event$0.Empty;
            "inventory.sync": event$0.Empty;
            "loggin": event$0.Empty;
            "logout": event$0.Empty;
            "reception": event$0.Empty;
            "stats:result": stats$0.Stats;
            "workflow.finished": event$0.Empty;
            "workflow.started": event$0.Empty;
        }
    }
}
