// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Empty {

    /** Creates a new Empty instance. */
    constructor($$source: Partial<Empty> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Empty instance from a string or object.
     */
    static createFrom($$source: any = {}): Empty {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Empty($$parsedSource as Partial<Empty>);
    }
}

export enum Topic {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WorkflowStarted = "workflow.started",
    Login = "loggin",

    /**
     * stats.Stats
     */
    Stats = "stats:result",
    GuidesGather = "guides.gather",
    InventorySync = "inventory.sync",
    Reception = "reception",
    Logout = "logout",
    WorkflowFinished = "workflow.finished",
    BuildingBrowser = "bulding.browser",
    DestroyingBrowser = "destroying.browser",
};
