// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Stats {
    "outstanding_debt": number;
    "intransit_guides": number;
    "expired_guides": number;
    "pending_procedures": number;

    /** Creates a new Stats instance. */
    constructor($$source: Partial<Stats> = {}) {
        if (!("outstanding_debt" in $$source)) {
            this["outstanding_debt"] = 0;
        }
        if (!("intransit_guides" in $$source)) {
            this["intransit_guides"] = 0;
        }
        if (!("expired_guides" in $$source)) {
            this["expired_guides"] = 0;
        }
        if (!("pending_procedures" in $$source)) {
            this["pending_procedures"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     */
    static createFrom($$source: any = {}): Stats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats($$parsedSource as Partial<Stats>);
    }
}
