// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "../auth/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../session/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close implements [SessionMediator].
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2716228199);
}

/**
 * Create implements [SessionMediator].
 */
export function Create(): $CancellablePromise<$models.Session> {
    return $Call.ByID(368151001);
}

/**
 * CreateIsolated implements [SessionMediator].
 */
export function CreateIsolated(parent: $models.Session): $CancellablePromise<$models.Session> {
    return $Call.ByID(1797453150, parent);
}

export function DeleteSession(id: $models.SessionID): $CancellablePromise<void> {
    return $Call.ByID(2200403554, id);
}

export function GetSession(id: $models.SessionID): $CancellablePromise<[$models.Session, boolean]> {
    return $Call.ByID(3029101109, id);
}

/**
 * Login implements [SessionMediator].
 */
export function Login(session: $models.Session, user: auth$0.User): $CancellablePromise<void> {
    return $Call.ByID(3691857294, session, user);
}

/**
 * Logout implements [SessionMediator].
 */
export function Logout(session: $models.Session): $CancellablePromise<void> {
    return $Call.ByID(1968003247, session);
}

/**
 * Reconfigure implements [SessionMediator].
 */
export function Reconfigure(cfg: config$0.BrowserConfig): $CancellablePromise<void> {
    return $Call.ByID(4066559144, cfg);
}
