// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package browser

import (
	"context"

	"github.com/Khaym03/REG/internal/config"
	"github.com/go-rod/rod"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrowserRuntime creates a new instance of MockBrowserRuntime. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrowserRuntime(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrowserRuntime {
	mock := &MockBrowserRuntime{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBrowserRuntime is an autogenerated mock type for the BrowserRuntime type
type MockBrowserRuntime struct {
	mock.Mock
}

type MockBrowserRuntime_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrowserRuntime) EXPECT() *MockBrowserRuntime_Expecter {
	return &MockBrowserRuntime_Expecter{mock: &_m.Mock}
}

// Browser provides a mock function for the type MockBrowserRuntime
func (_mock *MockBrowserRuntime) Browser() *rod.Browser {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Browser")
	}

	var r0 *rod.Browser
	if returnFunc, ok := ret.Get(0).(func() *rod.Browser); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rod.Browser)
		}
	}
	return r0
}

// MockBrowserRuntime_Browser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Browser'
type MockBrowserRuntime_Browser_Call struct {
	*mock.Call
}

// Browser is a helper method to define mock.On call
func (_e *MockBrowserRuntime_Expecter) Browser() *MockBrowserRuntime_Browser_Call {
	return &MockBrowserRuntime_Browser_Call{Call: _e.mock.On("Browser")}
}

func (_c *MockBrowserRuntime_Browser_Call) Run(run func()) *MockBrowserRuntime_Browser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrowserRuntime_Browser_Call) Return(browser *rod.Browser) *MockBrowserRuntime_Browser_Call {
	_c.Call.Return(browser)
	return _c
}

func (_c *MockBrowserRuntime_Browser_Call) RunAndReturn(run func() *rod.Browser) *MockBrowserRuntime_Browser_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBrowserRuntime
func (_mock *MockBrowserRuntime) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrowserRuntime_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBrowserRuntime_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBrowserRuntime_Expecter) Close() *MockBrowserRuntime_Close_Call {
	return &MockBrowserRuntime_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBrowserRuntime_Close_Call) Run(run func()) *MockBrowserRuntime_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBrowserRuntime_Close_Call) Return(err error) *MockBrowserRuntime_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrowserRuntime_Close_Call) RunAndReturn(run func() error) *MockBrowserRuntime_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Reconfigure provides a mock function for the type MockBrowserRuntime
func (_mock *MockBrowserRuntime) Reconfigure(ctx context.Context, cfg config.BrowserConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Reconfigure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.BrowserConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrowserRuntime_Reconfigure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconfigure'
type MockBrowserRuntime_Reconfigure_Call struct {
	*mock.Call
}

// Reconfigure is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg config.BrowserConfig
func (_e *MockBrowserRuntime_Expecter) Reconfigure(ctx interface{}, cfg interface{}) *MockBrowserRuntime_Reconfigure_Call {
	return &MockBrowserRuntime_Reconfigure_Call{Call: _e.mock.On("Reconfigure", ctx, cfg)}
}

func (_c *MockBrowserRuntime_Reconfigure_Call) Run(run func(ctx context.Context, cfg config.BrowserConfig)) *MockBrowserRuntime_Reconfigure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.BrowserConfig
		if args[1] != nil {
			arg1 = args[1].(config.BrowserConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrowserRuntime_Reconfigure_Call) Return(err error) *MockBrowserRuntime_Reconfigure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrowserRuntime_Reconfigure_Call) RunAndReturn(run func(ctx context.Context, cfg config.BrowserConfig) error) *MockBrowserRuntime_Reconfigure_Call {
	_c.Call.Return(run)
	return _c
}
