// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class DateRange {
    "from": time$0.Time;
    "to": time$0.Time;

    /** Creates a new DateRange instance. */
    constructor($$source: Partial<DateRange> = {}) {
        if (!("from" in $$source)) {
            this["from"] = null;
        }
        if (!("to" in $$source)) {
            this["to"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DateRange instance from a string or object.
     */
    static createFrom($$source: any = {}): DateRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DateRange($$parsedSource as Partial<DateRange>);
    }
}
