// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reception

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPage creates a new instance of MockPage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPage {
	mock := &MockPage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPage is an autogenerated mock type for the Page type
type MockPage struct {
	mock.Mock
}

type MockPage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPage) EXPECT() *MockPage_Expecter {
	return &MockPage_Expecter{mock: &_m.Mock}
}

// ApplyFilters provides a mock function for the type MockPage
func (_mock *MockPage) ApplyFilters(v DateRange) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for ApplyFilters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(DateRange) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPage_ApplyFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyFilters'
type MockPage_ApplyFilters_Call struct {
	*mock.Call
}

// ApplyFilters is a helper method to define mock.On call
//   - v DateRange
func (_e *MockPage_Expecter) ApplyFilters(v interface{}) *MockPage_ApplyFilters_Call {
	return &MockPage_ApplyFilters_Call{Call: _e.mock.On("ApplyFilters", v)}
}

func (_c *MockPage_ApplyFilters_Call) Run(run func(v DateRange)) *MockPage_ApplyFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 DateRange
		if args[0] != nil {
			arg0 = args[0].(DateRange)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPage_ApplyFilters_Call) Return(err error) *MockPage_ApplyFilters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPage_ApplyFilters_Call) RunAndReturn(run func(v DateRange) error) *MockPage_ApplyFilters_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmReception provides a mock function for the type MockPage
func (_mock *MockPage) ConfirmReception() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfirmReception")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPage_ConfirmReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmReception'
type MockPage_ConfirmReception_Call struct {
	*mock.Call
}

// ConfirmReception is a helper method to define mock.On call
func (_e *MockPage_Expecter) ConfirmReception() *MockPage_ConfirmReception_Call {
	return &MockPage_ConfirmReception_Call{Call: _e.mock.On("ConfirmReception")}
}

func (_c *MockPage_ConfirmReception_Call) Run(run func()) *MockPage_ConfirmReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPage_ConfirmReception_Call) Return(err error) *MockPage_ConfirmReception_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPage_ConfirmReception_Call) RunAndReturn(run func() error) *MockPage_ConfirmReception_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockPage
func (_mock *MockPage) Open() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPage_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockPage_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
func (_e *MockPage_Expecter) Open() *MockPage_Open_Call {
	return &MockPage_Open_Call{Call: _e.mock.On("Open")}
}

func (_c *MockPage_Open_Call) Run(run func()) *MockPage_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPage_Open_Call) Return(err error) *MockPage_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPage_Open_Call) RunAndReturn(run func() error) *MockPage_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Rows provides a mock function for the type MockPage
func (_mock *MockPage) Rows() ([]TableRow, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rows")
	}

	var r0 []TableRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]TableRow, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []TableRow); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TableRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPage_Rows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rows'
type MockPage_Rows_Call struct {
	*mock.Call
}

// Rows is a helper method to define mock.On call
func (_e *MockPage_Expecter) Rows() *MockPage_Rows_Call {
	return &MockPage_Rows_Call{Call: _e.mock.On("Rows")}
}

func (_c *MockPage_Rows_Call) Run(run func()) *MockPage_Rows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPage_Rows_Call) Return(tableRows []TableRow, err error) *MockPage_Rows_Call {
	_c.Call.Return(tableRows, err)
	return _c
}

func (_c *MockPage_Rows_Call) RunAndReturn(run func() ([]TableRow, error)) *MockPage_Rows_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTableRow creates a new instance of MockTableRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTableRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTableRow {
	mock := &MockTableRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTableRow is an autogenerated mock type for the TableRow type
type MockTableRow struct {
	mock.Mock
}

type MockTableRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTableRow) EXPECT() *MockTableRow_Expecter {
	return &MockTableRow_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockTableRow
func (_mock *MockTableRow) ID() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTableRow_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTableRow_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTableRow_Expecter) ID() *MockTableRow_ID_Call {
	return &MockTableRow_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTableRow_ID_Call) Run(run func()) *MockTableRow_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableRow_ID_Call) Return(s string, err error) *MockTableRow_ID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTableRow_ID_Call) RunAndReturn(run func() (string, error)) *MockTableRow_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsExpired provides a mock function for the type MockTableRow
func (_mock *MockTableRow) IsExpired() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsExpired")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTableRow_IsExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExpired'
type MockTableRow_IsExpired_Call struct {
	*mock.Call
}

// IsExpired is a helper method to define mock.On call
func (_e *MockTableRow_Expecter) IsExpired() *MockTableRow_IsExpired_Call {
	return &MockTableRow_IsExpired_Call{Call: _e.mock.On("IsExpired")}
}

func (_c *MockTableRow_IsExpired_Call) Run(run func()) *MockTableRow_IsExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableRow_IsExpired_Call) Return(b bool) *MockTableRow_IsExpired_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTableRow_IsExpired_Call) RunAndReturn(run func() bool) *MockTableRow_IsExpired_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerReception provides a mock function for the type MockTableRow
func (_mock *MockTableRow) TriggerReception() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TriggerReception")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTableRow_TriggerReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerReception'
type MockTableRow_TriggerReception_Call struct {
	*mock.Call
}

// TriggerReception is a helper method to define mock.On call
func (_e *MockTableRow_Expecter) TriggerReception() *MockTableRow_TriggerReception_Call {
	return &MockTableRow_TriggerReception_Call{Call: _e.mock.On("TriggerReception")}
}

func (_c *MockTableRow_TriggerReception_Call) Run(run func()) *MockTableRow_TriggerReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableRow_TriggerReception_Call) Return(err error) *MockTableRow_TriggerReception_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTableRow_TriggerReception_Call) RunAndReturn(run func() error) *MockTableRow_TriggerReception_Call {
	_c.Call.Return(run)
	return _c
}
