// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auth$0 from "./internal/auth/models.js";

export function AuthUser(user: auth$0.User): $CancellablePromise<void> {
    return $Call.ByID(2464313505, user);
}

export function CurrentUser(): $CancellablePromise<auth$0.RegisterUsers | null> {
    return $Call.ByID(1541159346).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetRegisterUsers(): $CancellablePromise<auth$0.RegisterUsers[]> {
    return $Call.ByID(2560311363).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetUserPassword(username: string): $CancellablePromise<auth$0.User> {
    return $Call.ByID(1146008310, username).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateUser(user: auth$0.RegisterUsers): $CancellablePromise<void> {
    return $Call.ByID(1968941006, user);
}

// Private type creation functions
const $$createType0 = auth$0.RegisterUsers.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = auth$0.User.createFrom;
