// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as event$0 from "./internal/event/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflow$0 from "./internal/workflow/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stats$0 from "./internal/workflow/queries/stats/models.js";

export function Ignore($0: stats$0.Stats, $1: event$0.Topic): $CancellablePromise<void> {
    return $Call.ByID(3165805115, $0, $1);
}

export function RunWorkflow(input: workflow$0.WorkFlowInput, browserConf: config$0.BrowserConfig): $CancellablePromise<void> {
    return $Call.ByID(3889876595, input, browserConf);
}

export function StopWorkflow(): $CancellablePromise<void> {
    return $Call.ByID(593648928);
}
