// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {app} from '../models';

export function GetUser():Promise<auth.User>;

export function RunWorkflow(arg1:app.WorkFlowInput):Promise<void>;

export function StopWorkflow():Promise<void>;
