// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {stats} from '../models';
import {workflow} from '../models';
import {config} from '../models';
import {event} from '../models';

export function GetUser():Promise<auth.User>;

export function Ignore(arg1:stats.Stats):Promise<void>;

export function RunWorkflow(arg1:workflow.WorkFlowInput,arg2:config.BrowserConfig):Promise<void>;

export function StopWorkflow():Promise<void>;

export function Topics():Promise<event.Topics>;
