// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function Ignore(arg1) {
  return window['go']['main']['App']['Ignore'](arg1);
}

export function RunWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2);
}

export function StopWorkflow() {
  return window['go']['main']['App']['StopWorkflow']();
}

export function Topics() {
  return window['go']['main']['App']['Topics']();
}
